### ISSUE TITLE
update

### ISSUE THREAD

**Issue by moreda-a** [SharifAIChallenge/AIC19-Doc#2]
توضيحات: درمانگر قهرماني با سرعت و سلامتي متوسط است. قابليت خاص اين قهرمان، درمانگري است كه ميتواند سلامتي يك
قهرمان خودي را حداكثر ٤٠ واحد تا مقدار سلامتي اوليه افزايش دهد.

not updated

**Comment by HamidH97** [comment]
در نسخه 1.3.1 برطرف شد
